#!/bin/bash

# Author: Emmanuel Ramos
# Date Created: 07/15/2023
# Last Modified: 07/15/2023

# Description
# Creates a backup in $destination folder of all files in the $HOME directory 

# Usage:
# backup_script

destination=~/backup_folder
mkdir $destination
tar -cvf $destination/my_backup_"$(date +%d-%m-%Y_%H-%M-%S)".tar ~/* 2>/dev/null
exit 0